# Permalinks
permalink:           pretty

# Setup
title:               Lena Dubov's Blog
tagline:             make the World better with data 
url:                 http://elena-du.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Elena Dubova
  url:               https://dubova.net
  email:             elena@dubova.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/elena-du

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
